### ISSUE TITLE
Chat doesn't work with lua

### ISSUE THREAD

**Issue by xtrome** [AllTheHaxx/Lua-Scripts#1]
As the title says, When I enable any lua I can't chat anymore and I have to disable all the lua to be able to chat again. Please fix!

**Comment by Henningstone** [comment]
Apparently you have to update your client!
https://github.com/AllTheHaxx/AllTheHaxx/releases/tag/0.15.1.1
Anyway, doesn't the auto-updater detect this update? If not I'm sorry, might have messed something up ._.

**Comment by xushWT** [comment]
Yup, you always should update your client before opening a issue.

Thanks for reporting anyways!

**Comment by xtrome** [comment]
Yeah but I guess you haven't update the main client at
https://allthehaxx.github.io/ :D
Auto update also seems to not be able to update it (failed to download an
update restart the client to retry)
No no I'm the one who should thank, I would probably struggle at it for a
long time if you didn't answer me :D

**Comment by Henningstone** [comment]
> Yeah but I guess you haven't update the main client at
https://allthehaxx.github.io/ :D
Nope I haven't, because that takes me a lot more work than just pushing an auto-update.

> Auto update also seems to not be able to update it (failed to download an
update restart the client to retry)
Then I actually messed up something ._. Sorry for that, gonna investigate it as soon as I have time again!

**Comment by Henningstone** [comment]
Hm... I just tested the auto-updater myself by downloading the latest release from our website, and it worked just fine...
Need to say that I'm on Linux, but I think it shouldn't make a big difference here :/

**Comment by Henningstone** [comment]
:arrow_forward:  here is a fix for the auto-updater on windows! https://git.io/vrQei

**Comment by xushWT** [comment]
Tanks

**Comment by xtrome** [comment]
Hey, sorry to disturb you again. May I have this lua file, in clc format?

AdvancedAimbotV2:
http://paste.ubuntu.com/23675533/

A lot of my friends are asking for it, and I can't share with them in lua
format because I don't want them to have source code.
That would be so nice of you if you do.

**Comment by xtrome** [comment]
hey... pls!

**Comment by xushWT** [comment]
Wow, ego. Wenn Share Thema source oft Thema whole Client too, you wont geht help here.


Ego.
